### PR TITLE
Feature/add mac notification

### PR DESCRIPTION
**Pull request by kamalhm**
Hi Mas @ariya , I saw this in the timeline and took a quick look and definitely interested in using this in my day-to-day, but turns out the notification doesn't support MacOS and Windows so I did a quick workaround using node-notifier dependency, I hope this helps!

I have tested this in MacOS and it works.

Please let me know if there's any suggestion :)

### CODE REVIEW

**Comment by ariya** [comment]
Hi @kamalhm, thank you for the PR!

While I like the idea, and in fact I did try it already in commit 25130df and also b4314c1, unfortunately it won't work well with the binary packaging. To see the problem yourself, rebase this feature branch to the latest main and then run `npm run build`. You will get the warning, e.g.

```
> Warning Cannot find module 'node-notifier' from …
```
But even worse, once the binary is produced, it won't run at all:
```
  Error: Cannot find module 'node-notifier'
```

I'm not sure if it's possible to fix it by tweaking how vercel/pkg is configured. But even if it's possible, seems that it's a bit of a hassle.

My suggestion: perhaps implement a simple macOS notification with osascript, see e.g. https://stackoverflow.com/questions/5588064/how-do-i-make-a-mac-terminal-pop-up-alert-applescript, similar to the Linux solution via notify-send.

**Comment by kamalhm** [comment]
I rebased my branch with the latest main and tried building it. While there were some warnings, I found the binary produced to be working well. Maybe it has something to do with me running the build on macOS? 

image
image


Meanwhile I'll look into your suggestions and hopefully I can implement that instead.

**Comment by ariya** [comment]
> Maybe it has something to do with me running the build on macOS?

Try running it on a different system (same OS) or at the very least, on a temporary empty directory.

**Comment by kamalhm** [comment]
Oh turns out it is broken when it's run on a directory without the node_modules. But I have fixed the PR using `osascript`, I tested it and it works even on an empty directory, please review again.

**Comment by ariya** [comment]
This is very good, thank you @kamalhm!

**Pull request merged**
